/**
 * For You feed 資料 Hook。
 * 今日 feed 為空時自動觸發一次產生（處理「app 在排程時間未開機」的情境）。
 */
import { useEffect, useRef } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { generateFeed, getFeed, sendFeedFeedback } from "../api/client";
import type { FeedFeedbackAction } from "../api/types";
import { queryKeys } from "../lib/react-query";

export function useFeed() {
  const queryClient = useQueryClient();
  // 每次 mount 至多自動 generate 一次，防 no-interests 時無限迴圈
  const autoGenerated = useRef(false);

  const query = useQuery({
    queryKey: queryKeys.feed.today(),
    queryFn: ({ signal }) => getFeed(signal),
  });

  const generateMutation = useMutation({
    mutationFn: generateFeed,
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: queryKeys.feed.today() });
    },
  });

  const feedbackMutation = useMutation({
    mutationFn: ({ itemId, action }: { itemId: number; action: FeedFeedbackAction }) =>
      sendFeedFeedback(itemId, action),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: queryKeys.feed.today() });
    },
  });

  const isEmpty = query.data !== undefined && query.data.items.length === 0;

  useEffect(() => {
    if (isEmpty && !autoGenerated.current && !generateMutation.isPending) {
      autoGenerated.current = true;
      generateMutation.mutate();
    }
  }, [isEmpty, generateMutation]);

  return {
    items: query.data?.items ?? [],
    feedDate: query.data?.feed_date ?? null,
    isLoading: query.isLoading || generateMutation.isPending,
    isGenerating: generateMutation.isPending,
    feedback: (itemId: number, action: FeedFeedbackAction) =>
      feedbackMutation.mutate({ itemId, action }),
    refresh: () => generateMutation.mutate(),
  };
}
