/**
 * For You feed 資料 Hook。
 * 今日 feed 為空時自動觸發一次產生（處理「app 在排程時間未開機」的情境）。
 */
import { useCallback, useEffect, useRef } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { generateFeed, getFeed, getFeedStats, sendFeedFeedback } from "../api/client";
import type { FeedFeedbackAction } from "../api/types";
import { queryKeys } from "../lib/react-query";

export function useFeed() {
  const queryClient = useQueryClient();
  // 每次 mount 至多自動 generate 一次，防 no-interests 時無限迴圈
  const autoGenerated = useRef(false);

  const query = useQuery({
    queryKey: queryKeys.feed.today(),
    queryFn: ({ signal }) => getFeed(signal),
  });

  const generateMutation = useMutation({
    mutationFn: generateFeed,
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: queryKeys.feed.today() });
    },
  });

  const feedbackMutation = useMutation({
    mutationFn: ({ itemId, action }: { itemId: number; action: FeedFeedbackAction }) =>
      sendFeedFeedback(itemId, action),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: queryKeys.feed.today() });
    },
  });

  // 成效摘要。獨立查詢而非併進 /feed：它涵蓋 30 天，而 feed 只是今天一批；
  // 綁在一起會讓「今天沒有 feed」連帶讓歷史統計消失，那正是最該看到它的時候。
  const statsQuery = useQuery({
    queryKey: queryKeys.feed.stats(),
    queryFn: ({ signal }) => getFeedStats(30, signal),
  });

  const isEmpty = query.data !== undefined && query.data.items.length === 0;

  // 呼叫當下即標記 autoGenerated，確保每次 mount 至多自動產生一次。
  const triggerGenerate = useCallback(() => {
    autoGenerated.current = true;
    generateMutation.mutate();
  }, [generateMutation]);

  useEffect(() => {
    if (isEmpty && !autoGenerated.current && !generateMutation.isPending) {
      triggerGenerate();
    }
  }, [isEmpty, generateMutation, triggerGenerate]);

  return {
    items: query.data?.items ?? [],
    feedDate: query.data?.feed_date ?? null,
    isLoading: query.isLoading || generateMutation.isPending,
    // 查詢與產生任一失敗都算錯誤：generate 掛掉時 query 會成功回傳空清單，
    // 若只看 query.isError 會把 API 失敗誤報成「還沒設定興趣」。
    isError: query.isError || generateMutation.isError,
    isGenerating: generateMutation.isPending,
    /** 近 30 天成效；還沒載到時為 null（不要用 0 佔位，那會被讀成真的是 0）*/
    stats: statsQuery.data ?? null,
    feedback: (itemId: number, action: FeedFeedbackAction) =>
      feedbackMutation.mutate({ itemId, action }),
  };
}
