name: Setup Sidecar
description: Set up Python, install dependencies, build sidecar binary, and copy to Tauri binaries

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: 'sidecar/requirements.txt'

    - name: Install sidecar dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r sidecar/requirements.txt
        pip install pyinstaller

    - name: Build sidecar binary
      shell: bash
      working-directory: sidecar
      run: pyinstaller starscope-sidecar.spec

    - name: Copy sidecar binary to Tauri binaries (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: cp sidecar/dist/starscope-sidecar-* src-tauri/binaries/

    - name: Copy sidecar binary to Tauri binaries (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: Copy-Item "sidecar\dist\starscope-sidecar-*.exe" -Destination "src-tauri\binaries\" -Force
