/**
 * For You feed 清單：Discovery 頁預設畫面。
 */
import { useI18n } from "../../i18n";
import { useFeed } from "../../hooks/useFeed";
import type { FeedItem } from "../../api/types";
import { FeedItemCard } from "./FeedItemCard";
import { Skeleton } from "../Skeleton";
import styles from "./Discovery.module.css";

interface ForYouFeedProps {
  onAddToWatchlist: (item: FeedItem) => Promise<boolean>;
}

export function ForYouFeed({ onAddToWatchlist }: ForYouFeedProps) {
  const { t } = useI18n();
  const { items, feedDate, isLoading, isGenerating, isError, feedback } = useFeed();

  if (isLoading) {
    return (
      <div className={styles.recSection} data-testid="for-you-feed">
        {isGenerating && <p className={styles.recSubtitle}>{t.discovery.forYou.generating}</p>}
        <Skeleton width="70%" height={16} style={{ marginBottom: 8 }} />
        <Skeleton width="100%" height={12} style={{ marginBottom: 12 }} />
        <Skeleton width="60%" height={14} />
      </div>
    );
  }

  // 不提供重試按鈕：feed 一天一批，有內容時後端冪等、無興趣時 generate 直接 return 0，
  // 兩種情況按了都不會有變化；而真正需要重試的「產生失敗」情境，離開頁面再回來就會
  // 重新掛載、autoGenerated ref 歸零並自動重試，不需要額外的按鈕。
  if (items.length === 0) {
    return (
      <div className={styles.emptyState} data-testid="feed-empty-state">
        {/* 區分「載入失敗」與「真的沒有內容」：兩者原本都顯示「請去設定新增興趣」，會把 API 錯誤誤報成沒設定 */}
        <p>{isError ? t.discovery.forYou.loadError : t.discovery.forYou.empty}</p>
      </div>
    );
  }

  const visible = items.filter((item) => item.feedback !== "dismissed");

  return (
    <div className={styles.recSection} data-testid="for-you-feed">
      <div className={styles.recSectionHeader}>
        <div>
          <h3>{t.discovery.forYou.title}</h3>
          <p className={styles.recSubtitle}>
            {t.discovery.forYou.subtitle}
            {feedDate && <span data-testid="feed-date"> · {feedDate}</span>}
          </p>
        </div>
      </div>
      {visible.length === 0 ? (
        <p className={styles.recSubtitle} data-testid="feed-all-dismissed">
          {t.discovery.forYou.allDismissed}
        </p>
      ) : (
        <div className={styles.resultsList}>
          {visible.map((item) => (
            <FeedItemCard
              key={item.id}
              item={item}
              onStar={async (it) => {
                // 只有加入 watchlist 成功才送出 starred feedback，避免失敗仍污染回饋訊號
                const success = await onAddToWatchlist(it);
                if (success) {
                  feedback(it.id, "starred");
                }
              }}
              onDismiss={(it) => feedback(it.id, "dismissed")}
            />
          ))}
        </div>
      )}
    </div>
  );
}
